version: '2'
services:
    couchbase:
        build:
            context: couchbase
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
        environment:
            - BUCKET=finance
#        volumes:
#            - ./couchbase/volume:/opt/couchbase/var
    fakeit:
        build:
            context: fakeit
        environment:
            - HOST=couchbase
            - BUCKET=finance
            - PASSWORD=password
            - TIMEOUT=10000
            - COUNT=10000
        volumes:
            - ../models:/data

    application:
        image: couchbase-finance-example
        environment:
            - SPRING_COUCHBASE_BOOTSTRAP-HOSTS=couchbase
            - SPRING_COUCHBASE_BUCKET_NAME=finance
            - SLEEP=30
        ports:
            - 8080:8080