version: '2'
services:
    couchbase:
        build:
            context: couchbase
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
        environment:
            - BUCKET=finance
#        volumes:
#            - ~/volumes/jhipster/jhipster/couchbase/:/opt/couchbase/var
    fakeit:
        build:
            context: fakeit
        environment:
            - HOST=couchbase
            - BUCKET=finance
            - PASSWORD=password
            - TIMEOUT=10000
            - COUNT=10000
        volumes:
            - ../models:/data